// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpUskgGfp-42svTJcUbJ-fIuI7yz2JJNc',
    appId: '1:271982533708:web:4b98119e64801a50cfe8e9',
    messagingSenderId: '271982533708',
    projectId: 'todo-app-project-ea6b1',
    authDomain: 'todo-app-project-ea6b1.firebaseapp.com',
    storageBucket: 'todo-app-project-ea6b1.appspot.com',
    measurementId: 'G-MPPF5F9EPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVNm2JfTcKcdUJrbV8aKCDASUZ6fn_Yrw',
    appId: '1:271982533708:android:043c2b902b453bc6cfe8e9',
    messagingSenderId: '271982533708',
    projectId: 'todo-app-project-ea6b1',
    storageBucket: 'todo-app-project-ea6b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7I2nefQ0lmNopDHVGSQfU7M8BJzbDM8w',
    appId: '1:271982533708:ios:5b93fbcf643a1da2cfe8e9',
    messagingSenderId: '271982533708',
    projectId: 'todo-app-project-ea6b1',
    storageBucket: 'todo-app-project-ea6b1.appspot.com',
    androidClientId: '271982533708-ioju4u13ouvmav2kdd8demefquk7vd0d.apps.googleusercontent.com',
    iosClientId: '271982533708-qjcapc02cimk0cj7fckuq29nu8agjl0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7I2nefQ0lmNopDHVGSQfU7M8BJzbDM8w',
    appId: '1:271982533708:ios:5b93fbcf643a1da2cfe8e9',
    messagingSenderId: '271982533708',
    projectId: 'todo-app-project-ea6b1',
    storageBucket: 'todo-app-project-ea6b1.appspot.com',
    androidClientId: '271982533708-ioju4u13ouvmav2kdd8demefquk7vd0d.apps.googleusercontent.com',
    iosClientId: '271982533708-qjcapc02cimk0cj7fckuq29nu8agjl0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpUskgGfp-42svTJcUbJ-fIuI7yz2JJNc',
    appId: '1:271982533708:web:d2ee8bba1455459dcfe8e9',
    messagingSenderId: '271982533708',
    projectId: 'todo-app-project-ea6b1',
    authDomain: 'todo-app-project-ea6b1.firebaseapp.com',
    storageBucket: 'todo-app-project-ea6b1.appspot.com',
    measurementId: 'G-5NQHP5HT3V',
  );
}
